baseURL: "https://louisedemoor.github.io" 
title: Louise Demoor
theme: PaperMod


enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: /papers/
          weight: 1 
        - name: Resume
          url: cv/
          weight: 2
        - name: Teaching
          url: courses/
          weight: 3
        - name: News
          url: news/
          weight: 4 


params:
    description: "I am a first year Ph.D. student in Economics at CREST."
    author: Louise Demoor
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    #MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Louise Demoor
          subtitle: "<div class="intro-text">
Welcome! I am a PhD student in Economics at
<a href="https://crest.science">CREST</a>
(<a href="https://www.polytechnique.edu">École Polytechnique</a>), advised by
<a href="https://sites.google.com/site/combeju/home">Julien Combe</a>.

<br><br>

My research area is
<a href="https://en.wikipedia.org/wiki/Market_design">market design</a>
(primarily theoretical). Currently, my main work is on kidney exchange and
teacher assignment in schools with distributional constraints.
</div> "
           #I am particularly interested in improving allocation systems by relaxing 
           #the traditional assumption that agents participate in these mechanisms in a fixed and exogenous way, and by identifying the factors that influence agents’ decisions to participate. 

          imageUrl: "picture.jpeg"
          imageWidth: 180
          imageHeight: 180
          buttons:
            - name: Research
              url: papers/
            - name:  Resume
              url: cv/
            - name : Teaching
              url: courses/
            - name: News
              url: news/
           # - name: Archive
            #  url: archive/

    socialIcons:
        - name: CV
          url: Academic_Resume.pdf
        - name: Email
          url: mailto:louise.demoor@polytechnique.edu
        - name: orcid
          url: https://orcid.org/0009-0008-3305-3375
        - name: Location
          url: location/
        #- name: GitHub
         # url: https://github.com/louisedemoor


    assets:
        disableHLJS: true
        disableScrollBarStyle: true
        favicon: "img/favicon.ico"
        favicon16x16: "img/favicon-16x16.png"
        favicon32x32: "img/favicon-32x32.png"
        apple_touch_icon: "img/apple-touch-icon.png"
        mask_icon: "img/favicon_safari.png"
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Louise Demoor"
      icon: img/favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2